// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCc7wey-icS4sgU4nrOsYu-45tF4ELoT4',
    appId: '1:372462576734:web:a3a430a4ae9b8e0ce1c0cf',
    messagingSenderId: '372462576734',
    projectId: 'topproject-51fea',
    authDomain: 'topproject-51fea.firebaseapp.com',
    storageBucket: 'topproject-51fea.firebasestorage.app',
    measurementId: 'G-9TDRH8KH1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVNLZeJTL2OrpkwA_eWDFmy_r417u7l8k',
    appId: '1:372462576734:android:83613ed2fcc235cfe1c0cf',
    messagingSenderId: '372462576734',
    projectId: 'topproject-51fea',
    storageBucket: 'topproject-51fea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOIR9Vv-VGlMr8dMsYkCUiHLTM03XHggI',
    appId: '1:372462576734:ios:a8617b7de5fe7042e1c0cf',
    messagingSenderId: '372462576734',
    projectId: 'topproject-51fea',
    storageBucket: 'topproject-51fea.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOIR9Vv-VGlMr8dMsYkCUiHLTM03XHggI',
    appId: '1:372462576734:ios:a8617b7de5fe7042e1c0cf',
    messagingSenderId: '372462576734',
    projectId: 'topproject-51fea',
    storageBucket: 'topproject-51fea.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCc7wey-icS4sgU4nrOsYu-45tF4ELoT4',
    appId: '1:372462576734:web:f6519bb2d1acd095e1c0cf',
    messagingSenderId: '372462576734',
    projectId: 'topproject-51fea',
    authDomain: 'topproject-51fea.firebaseapp.com',
    storageBucket: 'topproject-51fea.firebasestorage.app',
    measurementId: 'G-58L2EKVJVE',
  );
}
